#![cfg(test)]
use super::*;
use soroban_sdk::{
    symbol_short,
    testutils::{Address as _, Events},
    Address, BytesN, Env, Symbol, TryIntoVal, Val, Vec,
};

// We need the compiled swap_escrow WASM bytes to test deployment layout mapping
mod escrow_wasm {
    soroban_sdk::contractimport!(file = "../../target/wasm32v1-none/release/swap_escrow.wasm");
}

#[test]
fn test_factory_lifecycle_and_deployment() {
    let env = Env::default();
    env.mock_all_auths();

    // 1. Generate mockup mock testing addresses securely
    let admin = Address::generate(&env);
    let verifier = Address::generate(&env);
    let token = Address::generate(&env);
    let depositor = Address::generate(&env);
    let treasury = Address::generate(&env);

    // 2. Register the Escrow Factory contract using modern structural register syntax
    let factory_id = env.register(EscrowFactoryContract, ());
    let factory_client = EscrowFactoryContractClient::new(&env, &factory_id);

    // 3. Upload the underlying SwapEscrow WASM to the test environment to get its hash
    let escrow_wasm_hash = env.deployer().upload_contract_wasm(escrow_wasm::WASM);

    // 4. Test normal initialization
    factory_client.initialize(&admin, &escrow_wasm_hash);

    // --- ASSERT INITIALIZATION EVENT ---
    let init_event = env.events().all().pop_back().unwrap();
    assert_eq!(init_event.0, factory_id); // Contract emitter check
    assert_eq!(
        init_event.1,
        (Symbol::new(&env, "factory"), symbol_short!("init"))
            .try_into_val(&env)
            .unwrap()
    ); // Topics check

    // Unpack direct tuple payload
    let init_data: Vec<Val> = init_event.2.try_into_val(&env).unwrap();
    let parsed_admin: Address = init_data.get(0).unwrap().try_into_val(&env).unwrap();
    let parsed_wasm: BytesN<32> = init_data.get(1).unwrap().try_into_val(&env).unwrap();
    assert_eq!(parsed_admin, admin);
    assert_eq!(parsed_wasm, escrow_wasm_hash);

    // 5. Test double-initialization prevention using the autogenerated try_ variant
    let duplicate_init_result = factory_client.try_initialize(&admin, &escrow_wasm_hash);
    assert!(
        duplicate_init_result.is_err(),
        "Factory should reject duplicate initialization"
    );

    // 6. Test dynamic escrow deployment
    let salt = BytesN::from_array(&env, &[1u8; 32]);
    let swap_amount: i128 = 10_000_000;
    let timeout_timestamp: u64 = 1717171717;
    let fee_bps: u32 = 100; // 1%

    let deployed_escrow_address = factory_client.create_escrow(
        &salt,
        &verifier,
        &token,
        &depositor,
        &treasury,
        &swap_amount,
        &timeout_timestamp,
        &fee_bps,
    );

    // --- ASSERT CREATION EVENT ---
    let create_event = env.events().all().pop_back().unwrap();
    assert_eq!(create_event.0, factory_id);
    assert_eq!(
        create_event.1,
        (Symbol::new(&env, "factory"), Symbol::new(&env, "created"))
            .try_into_val(&env)
            .unwrap()
    );

    // Unpack direct tuple payload (escrow_address, depositor, swap_amount)
    let create_data: Vec<Val> = create_event.2.try_into_val(&env).unwrap();
    let parsed_escrow: Address = create_data.get(0).unwrap().try_into_val(&env).unwrap();
    let parsed_depositor: Address = create_data.get(1).unwrap().try_into_val(&env).unwrap();
    let parsed_amount: i128 = create_data.get(2).unwrap().try_into_val(&env).unwrap();

    assert_eq!(parsed_escrow, deployed_escrow_address);
    assert_eq!(parsed_depositor, depositor);
    assert_eq!(parsed_amount, swap_amount);

    // 7. Verify the deployed contract is an operational SwapEscrow instance and initialized
    let cloned_escrow_client = escrow_instance::Client::new(&env, &deployed_escrow_address);

    // Testing duplicate contract initialization verification via auto-generated try_ handles
    let duplicate_escrow_init = cloned_escrow_client.try_initialize(
        &admin,
        &verifier,
        &token,
        &depositor,
        &treasury,
        &swap_amount,
        &timeout_timestamp,
        &fee_bps,
    );
    assert!(
        duplicate_escrow_init.is_err(),
        "Cloned escrow should already be flagged initialized"
    );

    // 8. Test Upgradeability / WASM Hash updates
    let new_fake_wasm_hash = BytesN::from_array(&env, &[2u8; 32]);
    factory_client.update_wasm_hash(&new_fake_wasm_hash);

    // --- ASSERT UPGRADE EVENT ---
    let upgrade_event = env.events().all().pop_back().unwrap();
    assert_eq!(upgrade_event.0, factory_id);
    assert_eq!(
        upgrade_event.1,
        (Symbol::new(&env, "factory"), Symbol::new(&env, "upgraded"))
            .try_into_val(&env)
            .unwrap()
    );

    // Unpack direct tuple payload (old_wasm_hash, new_wasm_hash)
    let upgrade_data: Vec<Val> = upgrade_event.2.try_into_val(&env).unwrap();
    let parsed_old_wasm: BytesN<32> = upgrade_data.get(0).unwrap().try_into_val(&env).unwrap();
    let parsed_new_wasm: BytesN<32> = upgrade_data.get(1).unwrap().try_into_val(&env).unwrap();

    assert_eq!(parsed_old_wasm, escrow_wasm_hash);
    assert_eq!(parsed_new_wasm, new_fake_wasm_hash);
}
