#![cfg(test)]
use super::*;
use soroban_sdk::{testutils::Address as _, Address, BytesN, Env}; // <-- Trait imported via alias to allow generate()

// We need the compiled swap_escrow WASM bytes to test deployment layout mapping
mod escrow_wasm {
    soroban_sdk::contractimport!(file = "../../target/wasm32v1-none/release/swap_escrow.wasm");
}

#[test]
fn test_factory_lifecycle_and_deployment() {
    let env = Env::default();
    env.mock_all_auths();

    // 1. Generate mockup mock testing addresses securely
    let admin = Address::generate(&env);
    let verifier = Address::generate(&env);
    let token = Address::generate(&env);
    let depositor = Address::generate(&env);
    let treasury = Address::generate(&env);

    // 2. Register the Escrow Factory contract using modern structural register syntax
    let factory_id = env.register(EscrowFactoryContract, ());
    let factory_client = EscrowFactoryContractClient::new(&env, &factory_id);

    // 3. Upload the underlying SwapEscrow WASM to the test environment to get its hash
    let escrow_wasm_hash = env.deployer().upload_contract_wasm(escrow_wasm::WASM);

    // 4. Test normal initialization
    factory_client.initialize(&admin, &escrow_wasm_hash);

    // 5. Test double-initialization prevention using the autogenerated try_ variant
    let duplicate_init_result = factory_client.try_initialize(&admin, &escrow_wasm_hash);
    assert!(
        duplicate_init_result.is_err(),
        "Factory should reject duplicate initialization"
    );

    // 6. Test dynamic escrow deployment
    let salt = BytesN::from_array(&env, &[1u8; 32]);
    let swap_amount: i128 = 10_000_000;
    let timeout_timestamp: u64 = 1717171717;
    let fee_bps: u32 = 100; // 1%

    let deployed_escrow_address = factory_client.create_escrow(
        &salt,
        &verifier,
        &token,
        &depositor,
        &treasury,
        &swap_amount,
        &timeout_timestamp,
        &fee_bps,
    );

    // 7. Verify the deployed contract is an operational SwapEscrow instance and initialized
    let cloned_escrow_client = escrow_instance::Client::new(&env, &deployed_escrow_address);

    // Testing duplicate contract initialization verification via auto-generated try_ handles
    let duplicate_escrow_init = cloned_escrow_client.try_initialize(
        &admin,
        &verifier,
        &token,
        &depositor,
        &treasury,
        &swap_amount,
        &timeout_timestamp,
        &fee_bps,
    );
    assert!(
        duplicate_escrow_init.is_err(),
        "Cloned escrow should already be flagged initialized"
    );

    // 8. Test Upgradeability / WASM Hash updates
    let new_fake_wasm_hash = BytesN::from_array(&env, &[2u8; 32]);
    factory_client.update_wasm_hash(&new_fake_wasm_hash);
}
